Extra summaries
maho3/ltu-cmass pull request #56
Opened 2024-08-21 14:29 UTC by florpi

Interfaced ltu-cmass diagnosis with ili-summarizer. I left summaries that are fast to compute as default summaries, but there are a couple of odd things:

- My redshift space haloes look odd, like RSD is not doing anything (the quadrupole is basically zero) but I’m not sure if this is due to charm or something else. The RSD implementation should be the same as before: https://github.com/maho3/ltu-cmass/blob/extra_summaries/cmass/diagnostics/tools.py#L6
- Bk gives the strangest errors, but given that Pk looks odd it might be due to the data vector being weird.
- The four summaries computed now take about 3 minutes in a cpu to compute for both configuration and redshift space. It should be faster on a gpu, particularly WST. Density Split is slow, since it computes lots of cross correlations, therefore I left it out for now.
- The binning of each summary statistic is now kind of arbitrary and people should play around with them

2024-09-11 13:51 UTC, DeaglanBartlett commented
Just noting here that the `summarizer` module is needed for this but is not mentioned in the installation notes, so this should be added.

2024-09-16 20:17 UTC, DeaglanBartlett commented on cmass/diagnostics/summ.py
> +                    store_summary(box_catalogue, group, summ, L, N, threads, rsd=False,)
`rsd` kwargs should be `use_rsd`

2024-09-16 20:17 UTC, DeaglanBartlett commented on cmass/diagnostics/summ.py
> +                    store_summary(zbox_catalogue, group, summ, L, N, threads, rsd=True,)
`rsd` kwargs should be `use_rsd`

2024-09-16 20:17 UTC, DeaglanBartlett commented on cmass/diagnostics/summ.py
> +                    store_summary(box_catalogue, group, summ, L, N, threads, rsd=False,)
`rsd` kwargs should be `use_rsd`

2024-09-16 20:17 UTC, DeaglanBartlett commented on cmass/diagnostics/summ.py
> +                    store_summary(zbox_catalogue, group, summ, L, N, threads, rsd=True,)
`rsd` kwargs should be `use_rsd`

2024-09-16 20:20 UTC, DeaglanBartlett commented on cmass/diagnostics/summ.py
> +import summarizer
When using pycorr as called by summarizer, I need to install from DESI rather than pip directly
```
pip install git+https://github.com/adematti/Corrfunc@desi
```
and then edit https://github.com/cosmodesi/pycorr/blob/29df2c2d700df77781f20c125e982fbf3ffe9daf/pycorr/corrfunc.py#L107-L114 to be
```
#if attrs.pop('gpu', False):
#    kwargs['gpu'] = True
kwargs['gpu'] = attrs.pop('gpu', False)
```

This should be included in the installation instructions or (better) fixed in `pycorr.`

2024-09-16 20:21 UTC, DeaglanBartlett commented on cmass/diagnostics/summ.py
> +             from_scratch=True,  summaries=['Pk','TwoPCF','KNN','WST']):
When running KNN, I obtain the error 
```
Traceback (most recent call last):
  File "/home/x-dbartlett/ltu-cmass/cmass/diagnostics/summ.py", line 263, in main
    done = halo_summ(
  File "/home/x-dbartlett/ltu-cmass/cmass/diagnostics/summ.py", line 176, in halo_summ
    store_summary(box_catalogue, group, summ, L, N, threads, use_rsd=False,)
  File "/home/x-dbartlett/ltu-cmass/cmass/diagnostics/summ.py", line 134, in store_summary
    summary_data = summary_function(catalog)
  File "/home/x-dbartlett/ili-summarizer/summarizer/knn/knn.py", line 46, in __call__
    return get_CDFkNN(
  File "/home/x-dbartlett/ili-summarizer/summarizer/knn/compute_knn.py", line 129, in get_CDFkNN
    volume_for_k = get_volume_knn(
  File "/home/x-dbartlett/ili-summarizer/summarizer/knn/compute_knn.py", line 97, in get_volume_knn
    tree = cKDTree(pos, boxsize=boxsize)
  File "_ckdtree.pyx", line 587, in scipy.spatial._ckdtree.cKDTree.__init__
ValueError: Some input data are greater than the size of the periodic box.
```
Given the pinocchio simulation used here was run with the correct volume, I do not see why this error has been raised.

2024-09-16 20:52 UTC, DeaglanBartlett commented on cmass/diagnostics/summ.py
> +             from_scratch=True,  summaries=['Pk','TwoPCF','KNN','WST']):
This has been fixed by adding in a mask such that only halos with all three coordinates in range [0,boxsize) are considered.

2024-09-16 21:00 UTC, florpi commented on cmass/diagnostics/summ.py
> +             from_scratch=True,  summaries=['Pk','TwoPCF','KNN','WST']):
should we wrap them inside the box with %boxsize? why are there haloes outside of the box?

2024-09-16 21:02 UTC, DeaglanBartlett commented on cmass/diagnostics/summ.py
> +             from_scratch=True,  summaries=['Pk','TwoPCF','KNN','WST']):
I just implemented a cut. There weren't really any outside the box when I checked, but there was at least one point with coordinate exactly equal to boxsize, but the kNN code requires all coordinates < this, not <=

2024-09-16 21:27 UTC, DeaglanBartlett requested changes

2024-09-16 21:27 UTC, DeaglanBartlett commented on cmass/diagnostics/summ.py
> +                zbox_catalogue = get_box_catalogue_rsd(pos=hpos, vel=hvel, h=h, z=z, axis=2, L=L, N=N)
This gives an error for me
```
 File "/home/x-dbartlett/ltu-cmass/cmass/diagnostics/summ.py", line 60, in get_box_catalogue_rsd
    pos = get_redshift_space_pos(pos=pos, vel=vel, z=z, h=h, axis=axis, L=L,)
  File "/home/x-dbartlett/ltu-cmass/cmass/diagnostics/tools.py", line 8, in get_redshift_space_pos
    RSL.pos_redshift_space(pos, vel, L, h*100, z, axis)
  File "library/redshift_space_library/redshift_space_library.pyx", line 29, in redshift_space_library.redshift_space_library.pos_redshift_space
ValueError: Buffer dtype mismatch, expected 'float' but got 'double'
```
Please ensure correct type is passed to the relevant function

2024-09-17 13:23 UTC, DeaglanBartlett commented on cmass/diagnostics/summ.py
> +                zbox_catalogue = get_box_catalogue_rsd(pos=hpos, vel=hvel, h=h, z=z, axis=2, L=L, N=N)
This has now been fixed by ensuring `pos` and `vel` are of dtype `np.float32`.

2024-09-17 14:52 UTC, DeaglanBartlett commented
I have now run the code on the pinocchio simulations with lhid=3 for the quijotelike suite, having run HOD before this:
```bash
python -m cmass.bias.apply_hod nbody=pinocchio_quijote sim=pinocchio
python -m cmass.diagnostics.summ nbody=pinocchio_quijote sim=pinocchio
```

Plotting the results gives the following for the halos:

![halos_pk](https://github.com/user-attachments/assets/6ee955d1-9fdb-4906-a532-413258e7fa9a)
![halos_twopcf](https://github.com/user-attachments/assets/a97f43d8-7e0f-4771-9f15-04792edc7cfc)
![halos_knn](https://github.com/user-attachments/assets/5d51222e-2c08-4d67-8813-2eabfbfb60f2)
![halos_hist](https://github.com/user-attachments/assets/ddc4c231-cdbe-4260-97aa-7e554ca7272c)

and for galaxies:

![galaxies_pk](https://github.com/user-attachments/assets/a3601f93-5b1d-4389-b440-9f6edeac16bc)
![galaxies_twopcf](https://github.com/user-attachments/assets/9187638c-3d30-489a-8d1e-4e1de96113af)
![galaxies_knn](https://github.com/user-attachments/assets/279e853d-cc4d-4a2d-ab1d-8445e97c8006)

2024-09-17 15:20 UTC, DeaglanBartlett commented
And here are the plots for $r^2 \xi(r)$ for halos:

![halos_twopcf (1)](https://github.com/user-attachments/assets/96bbe64f-f2ed-4b48-b52a-ddd302674443)

and galaxies:

![galaxies_twopcf (1)](https://github.com/user-attachments/assets/022a1266-c2b1-4798-9a56-18afcade2ec7)

2024-09-17 15:28 UTC, DeaglanBartlett commented on cmass/diagnostics/summ.py
> +import summarizer
I have included this discussion into the installation instructions for summarizer

2024-09-17 15:31 UTC, DeaglanBartlett approved these changes

2024-09-17 15:31 UTC, merged